name: Run Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgresql:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: password123
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - "5444:5432"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Copy test config.yaml
      run: cp config.yaml.example config.test.yaml

    - name: Build
      run: go build -v ./...

    - name: Prepare database
      run: go run . -config config.test.yaml -migrate

    - name: Test
      run: go test -v ./...
